### ISSUE TITLE
is it possible to use this to create a collection from a *music* playlist…?

### ISSUE THREAD

**Issue by danielletx** [danrahn/PlexPlaylistToCollection#2]
i have almost 100 music playlists that i'd like to individually convert to plex collections so i don't have to share each one individually with each different user (a tedious task, to be sure—and what's worse is that it can't be done in bulk). does your tool support artists/albums/tracks on playlists as well…?

**Comment by danrahn** [comment]
It didn't, but it should support music playlists as of this change: https://github.com/danrahn/PlexPlaylistToCollection/commit/bef3f1e2983d8f43648cbefabc183a2a676f8a6b. Let me know if it doesn't work for you, since I only did some _very_ basic testing on my end.
