### ISSUE TITLE
Getting Error in Ubuntu 20.04

### ISSUE THREAD

**Issue by influx3k** [danrahn/PlexPlaylistToCollection#3]
Tried running this script, but am getting the following error in Ubuntu 20.04:

`plex@plex:~/Scripts/PlexPlaylistToCollection$ python3 PlexPlaylistToCollection.py
  File "PlexPlaylistToCollection.py", line 225
    match item['type']:
          ^
`

Would love to use this, so any help would be appreciated!

**Comment by danrahn** [comment]
What version of Python are you using? 3.10 or greater is required.

**Comment by influx3k** [comment]
I have Python 3.8.10.  Just realized that was outdated.  I guess I saw it as 3.1.0, but it's 3.10.

**Comment by influx3k** [comment]
Got it sorted.  Thanks!
